### ISSUE TITLE
Partial functionality depending on how you open a file

### ISSUE THREAD

**Issue by feldoh** [Garethp/Rider-RimworldDevelopment#1]
When you have a CSharp project which has mounted a defs folder as an "Existing Item" with a link, if you open an XML file from the link you get more functionality than when you open that same file from the other project.

![image](https://user-images.githubusercontent.com/3587179/193429798-1e8f7b28-b3cb-4da4-98e0-2b4049052b72.png)

When editing from the link we see supertype fields like `index` and `description`
![image](https://user-images.githubusercontent.com/3587179/193429820-573c5ea7-c84f-4c54-8791-5603fc25c1f0.png)

But the same file when edited directly not via the link does not show these fields
![image](https://user-images.githubusercontent.com/3587179/193429833-6e14f41d-0fff-4b9a-8dd4-68f5c265d857.png)

**Comment by Garethp** [comment]
I think I've managed to solve this issue in Alpha-3. Can you check to see if it's properly fixed?

**Comment by feldoh** [comment]
confirmed
