### ISSUE TITLE
Def autocomplete issues with namespaces

### ISSUE THREAD

**Issue by joseasoler** [Garethp/Rider-RimworldDevelopment#3]
Def autocomplete has issues with Defs placed inside namespaces. For example, [TraderGen](https://gitlab.com/joseasoler/tradergen) has a custom TG.TraderSpecializationDef. After typing `<TG` at [this line of the project](https://gitlab.com/joseasoler/tradergen/-/blob/main/1.4/Defs/TraderSpecializationDefs/TG_Specializations.xml#L3), Rider-RimworldDevelopment autocomplete shows <TG.TraderSpecializationDef> as the last option. When I type the ., it will just autocomplete to OrderedTakeGroupDef instead.

**Comment by Garethp** [comment]
This has been merged into `2023.4` and will be released with that
